Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    fc1:
      Precision:
        bias: fixed<5,1>
        result: fixed<16,6>
        weight: fixed<5,1>
      Trace: false
    fc1_input:
      Precision:
        result: fixed<16,2>
      Trace: false
    fc1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    fc2:
      Precision:
        bias: fixed<5,1>
        result: fixed<16,6>
        weight: fixed<5,1>
      Trace: false
    fc2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        bias: fixed<5,1>
        result: fixed<16,6>
        weight: fixed<5,1>
      Trace: false
    output_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: ufixed<5,0,RND_CONV,SAT>
      Trace: false
    relu2:
      Precision:
        result: ufixed<5,0,RND_CONV,SAT>
      Trace: false
    softmax:
      Precision:
        result: fixed<16,2>
      Trace: false
      exp_table_t: ap_fixed<18,8>
      inv_table_t: ap_fixed<18,4>
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model './Models/precision_test/3/hls_prj/keras_model.h5'
OutputDir: ./Models/precision_test/3/hls_prj
OutputPredictions: null
Part: xc7a35tcsg324
ProjectName: NN_precision_3
Stamp: 226EC3eF
Version: 1.0.0
