// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_5_V_read,
        data_6_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [4:0] data_0_V_read;
input  [4:0] data_1_V_read;
input  [4:0] data_2_V_read;
input  [4:0] data_5_V_read;
input  [4:0] data_6_V_read;
input  [4:0] data_8_V_read;
input  [4:0] data_9_V_read;
input  [4:0] data_10_V_read;
input  [4:0] data_11_V_read;
input  [4:0] data_13_V_read;
input  [4:0] data_14_V_read;
input  [4:0] data_15_V_read;
input  [4:0] data_16_V_read;
input  [4:0] data_17_V_read;
input  [4:0] data_18_V_read;
input  [4:0] data_19_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;

wire   [9:0] mul_ln1118_fu_181_p2;
reg   [9:0] mul_ln1118_reg_429;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] mul_ln1118_3_fu_183_p2;
reg   [9:0] mul_ln1118_3_reg_433;
reg   [4:0] data_8_V_read_3_reg_1358;
reg   [4:0] data_6_V_read_3_reg_1364;
reg   [4:0] data_0_V_read_3_reg_1370;
wire   [9:0] sub_ln1118_1_fu_467_p2;
reg   [9:0] sub_ln1118_1_reg_1375;
wire   [9:0] sub_ln1118_14_fu_866_p2;
reg   [9:0] sub_ln1118_14_reg_1380;
wire   [9:0] sub_ln1118_15_fu_884_p2;
reg   [9:0] sub_ln1118_15_reg_1385;
wire   [9:0] sub_ln1118_18_fu_936_p2;
reg   [9:0] sub_ln1118_18_reg_1390;
wire   [11:0] add_ln703_fu_972_p2;
reg   [11:0] add_ln703_reg_1395;
wire   [11:0] add_ln703_3_fu_978_p2;
reg   [11:0] add_ln703_3_reg_1400;
reg   [11:0] add_ln703_3_reg_1400_pp0_iter1_reg;
wire   [10:0] add_ln703_8_fu_984_p2;
reg   [10:0] add_ln703_8_reg_1405;
wire   [11:0] add_ln703_10_fu_990_p2;
reg   [11:0] add_ln703_10_reg_1410;
wire   [11:0] add_ln703_11_fu_996_p2;
reg   [11:0] add_ln703_11_reg_1415;
wire   [11:0] add_ln703_16_fu_1002_p2;
reg   [11:0] add_ln703_16_reg_1420;
wire   [11:0] add_ln703_18_fu_1008_p2;
reg   [11:0] add_ln703_18_reg_1425;
wire   [11:0] add_ln703_20_fu_1014_p2;
reg   [11:0] add_ln703_20_reg_1430;
wire   [12:0] add_ln703_2_fu_1184_p2;
reg   [12:0] add_ln703_2_reg_1435;
wire   [12:0] add_ln703_5_fu_1200_p2;
reg   [12:0] add_ln703_5_reg_1440;
wire   [12:0] add_ln703_9_fu_1213_p2;
reg   [12:0] add_ln703_9_reg_1445;
wire   [12:0] add_ln703_13_fu_1231_p2;
reg   [12:0] add_ln703_13_reg_1450;
wire   [12:0] add_ln703_17_fu_1250_p2;
reg   [12:0] add_ln703_17_reg_1455;
wire   [12:0] add_ln703_19_fu_1259_p2;
reg   [12:0] add_ln703_19_reg_1460;
wire   [12:0] add_ln703_21_fu_1268_p2;
reg   [12:0] add_ln703_21_reg_1465;
wire   [4:0] mul_ln1118_fu_181_p0;
wire    ap_block_pp0_stage0;
wire   [4:0] mul_ln1118_3_fu_183_p0;
wire   [9:0] zext_ln1116_4_fu_697_p1;
wire   [8:0] shl_ln1118_4_fu_443_p3;
wire   [6:0] shl_ln1118_5_fu_455_p3;
wire   [9:0] zext_ln1118_2_fu_463_p1;
wire   [9:0] zext_ln1118_1_fu_451_p1;
wire   [8:0] shl_ln1118_7_fu_473_p3;
wire   [9:0] zext_ln1118_3_fu_481_p1;
wire   [9:0] sub_ln1118_2_fu_485_p2;
wire   [10:0] shl_ln728_6_fu_491_p3;
wire   [5:0] shl_ln1118_s_fu_503_p3;
wire   [6:0] zext_ln1118_6_fu_511_p1;
wire   [6:0] sub_ln1118_4_fu_515_p2;
wire   [7:0] shl_ln728_8_fu_521_p3;
wire   [7:0] shl_ln1118_1_fu_533_p3;
wire   [5:0] shl_ln1118_2_fu_545_p3;
wire   [8:0] zext_ln1118_8_fu_553_p1;
wire   [8:0] zext_ln1118_7_fu_541_p1;
wire   [8:0] sub_ln1118_5_fu_557_p2;
wire   [9:0] shl_ln728_9_fu_563_p3;
wire   [8:0] shl_ln1118_10_fu_579_p3;
wire   [9:0] zext_ln1118_10_fu_587_p1;
wire   [9:0] zext_ln1116_2_fu_575_p1;
wire   [9:0] sub_ln1118_7_fu_591_p2;
wire   [10:0] shl_ln728_3_fu_597_p3;
wire   [8:0] shl_ln728_4_fu_609_p3;
wire   [8:0] shl_ln1118_11_fu_621_p3;
wire   [9:0] zext_ln1118_11_fu_629_p1;
wire   [9:0] sub_ln1118_8_fu_633_p2;
wire   [10:0] shl_ln728_5_fu_639_p3;
wire   [7:0] shl_ln728_10_fu_651_p3;
wire   [8:0] tmp_1_fu_667_p3;
wire   [9:0] zext_ln1116_3_fu_663_p1;
wire   [9:0] zext_ln1118_12_fu_675_p1;
wire   [9:0] sub_ln1118_9_fu_679_p2;
wire   [10:0] shl_ln728_11_fu_685_p3;
wire   [8:0] shl_ln1118_12_fu_702_p3;
wire   [9:0] zext_ln1118_13_fu_710_p1;
wire   [9:0] sub_ln1118_10_fu_714_p2;
wire   [10:0] shl_ln728_12_fu_720_p3;
wire   [7:0] shl_ln728_14_fu_732_p3;
wire   [8:0] shl_ln1118_13_fu_744_p3;
wire   [9:0] zext_ln1118_14_fu_752_p1;
wire   [9:0] sub_ln1118_11_fu_756_p2;
wire   [10:0] shl_ln728_15_fu_762_p3;
wire   [8:0] shl_ln1118_14_fu_774_p3;
wire   [9:0] zext_ln1118_15_fu_782_p1;
wire   [9:0] sub_ln1118_12_fu_786_p2;
wire   [10:0] shl_ln728_16_fu_792_p3;
wire   [7:0] shl_ln1118_15_fu_804_p3;
wire   [5:0] shl_ln1118_16_fu_816_p3;
wire   [8:0] zext_ln1118_17_fu_824_p1;
wire   [8:0] zext_ln1118_16_fu_812_p1;
wire   [8:0] sub_ln1118_13_fu_828_p2;
wire   [9:0] shl_ln728_17_fu_834_p3;
wire   [8:0] shl_ln1118_17_fu_854_p3;
wire   [9:0] zext_ln1118_19_fu_862_p1;
wire   [9:0] zext_ln1116_5_fu_846_p1;
wire   [5:0] shl_ln1118_18_fu_872_p3;
wire   [9:0] zext_ln1118_20_fu_880_p1;
wire   [7:0] tmp_2_fu_890_p3;
wire   [8:0] zext_ln1118_18_fu_850_p1;
wire   [8:0] zext_ln1118_21_fu_898_p1;
wire   [8:0] sub_ln1118_16_fu_902_p2;
wire   [9:0] shl_ln728_20_fu_908_p3;
wire   [8:0] tmp_3_fu_924_p3;
wire   [9:0] zext_ln1116_6_fu_920_p1;
wire   [9:0] zext_ln1118_22_fu_932_p1;
wire   [5:0] shl_ln1118_19_fu_942_p3;
wire   [9:0] zext_ln1118_23_fu_950_p1;
wire   [9:0] sub_ln1118_17_fu_954_p2;
wire   [10:0] shl_ln728_22_fu_960_p3;
wire  signed [11:0] sext_ln728_5_fu_647_p1;
wire  signed [11:0] sext_ln728_6_fu_693_p1;
wire   [11:0] zext_ln728_4_fu_728_p1;
wire   [11:0] zext_ln728_5_fu_740_p1;
wire  signed [10:0] sext_ln728_4_fu_571_p1;
wire   [10:0] zext_ln728_2_fu_617_p1;
wire  signed [11:0] sext_ln728_8_fu_770_p1;
wire  signed [11:0] sext_ln728_10_fu_842_p1;
wire   [11:0] zext_ln728_7_fu_968_p1;
wire  signed [11:0] sext_ln728_2_fu_499_p1;
wire  signed [11:0] sext_ln728_3_fu_529_p1;
wire   [11:0] zext_ln728_1_fu_605_p1;
wire   [11:0] zext_ln728_3_fu_659_p1;
wire  signed [11:0] sext_ln728_9_fu_800_p1;
wire  signed [11:0] sext_ln728_12_fu_916_p1;
wire   [8:0] shl_ln1118_3_fu_1020_p3;
wire   [9:0] zext_ln1118_fu_1027_p1;
wire   [9:0] sub_ln1118_fu_1031_p2;
wire   [10:0] shl_ln728_1_fu_1045_p3;
wire   [10:0] shl_ln728_2_fu_1057_p3;
wire   [8:0] shl_ln1118_8_fu_1068_p3;
wire   [6:0] shl_ln1118_9_fu_1079_p3;
wire   [9:0] zext_ln1118_4_fu_1075_p1;
wire   [9:0] zext_ln1118_5_fu_1086_p1;
wire   [9:0] sub_ln1118_3_fu_1090_p2;
wire   [8:0] shl_ln1118_6_fu_1107_p3;
wire   [9:0] zext_ln1118_9_fu_1114_p1;
wire   [9:0] zext_ln1116_1_fu_1104_p1;
wire   [9:0] sub_ln1118_6_fu_1118_p2;
wire   [10:0] shl_ln728_s_fu_1124_p3;
wire   [10:0] shl_ln728_13_fu_1136_p3;
wire   [10:0] shl_ln728_18_fu_1148_p3;
wire   [10:0] shl_ln728_19_fu_1159_p3;
wire   [10:0] shl_ln_fu_1037_p3;
wire  signed [12:0] sext_ln703_4_fu_1181_p1;
wire  signed [12:0] sext_ln703_fu_1177_p1;
wire   [10:0] shl_ln728_21_fu_1170_p3;
wire   [10:0] add_ln703_4_fu_1190_p2;
wire  signed [12:0] sext_ln703_6_fu_1196_p1;
wire   [12:0] zext_ln728_6_fu_1155_p1;
wire   [10:0] shl_ln728_7_fu_1096_p3;
wire  signed [12:0] sext_ln703_9_fu_1210_p1;
wire   [12:0] zext_ln703_3_fu_1206_p1;
wire  signed [12:0] sext_ln703_12_fu_1222_p1;
wire  signed [12:0] sext_ln728_11_fu_1166_p1;
wire   [12:0] add_ln703_12_fu_1225_p2;
wire  signed [12:0] sext_ln703_11_fu_1219_p1;
wire  signed [11:0] sext_ln728_1_fu_1064_p1;
wire  signed [11:0] sext_ln728_fu_1053_p1;
wire   [11:0] add_ln703_15_fu_1237_p2;
wire  signed [12:0] sext_ln703_16_fu_1247_p1;
wire  signed [12:0] sext_ln703_15_fu_1243_p1;
wire   [12:0] zext_ln703_1_fu_1256_p1;
wire   [12:0] zext_ln728_fu_1132_p1;
wire  signed [12:0] sext_ln703_18_fu_1265_p1;
wire  signed [12:0] sext_ln728_7_fu_1144_p1;
wire  signed [13:0] sext_ln703_7_fu_1280_p1;
wire   [13:0] zext_ln703_fu_1277_p1;
wire   [13:0] add_ln703_6_fu_1283_p2;
wire  signed [13:0] sext_ln703_5_fu_1274_p1;
wire   [13:0] add_ln703_7_fu_1289_p2;
wire  signed [13:0] sext_ln703_13_fu_1302_p1;
wire  signed [13:0] sext_ln703_10_fu_1299_p1;
wire   [13:0] acc_1_V_fu_1305_p2;
wire  signed [13:0] sext_ln703_19_fu_1321_p1;
wire   [13:0] zext_ln703_2_fu_1318_p1;
wire   [13:0] add_ln703_22_fu_1324_p2;
wire  signed [13:0] sext_ln703_17_fu_1315_p1;
wire   [13:0] acc_2_V_fu_1330_p2;
wire  signed [15:0] sext_ln703_8_fu_1295_p1;
wire  signed [15:0] sext_ln703_14_fu_1311_p1;
wire  signed [15:0] sext_ln703_20_fu_1336_p1;
reg    ap_ce_reg;
reg   [4:0] data_0_V_read_int_reg;
reg   [4:0] data_1_V_read_int_reg;
reg   [4:0] data_2_V_read_int_reg;
reg   [4:0] data_5_V_read_int_reg;
reg   [4:0] data_6_V_read_int_reg;
reg   [4:0] data_8_V_read_int_reg;
reg   [4:0] data_9_V_read_int_reg;
reg   [4:0] data_10_V_read_int_reg;
reg   [4:0] data_11_V_read_int_reg;
reg   [4:0] data_13_V_read_int_reg;
reg   [4:0] data_14_V_read_int_reg;
reg   [4:0] data_15_V_read_int_reg;
reg   [4:0] data_16_V_read_int_reg;
reg   [4:0] data_17_V_read_int_reg;
reg   [4:0] data_18_V_read_int_reg;
reg   [4:0] data_19_V_read_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
wire   [9:0] mul_ln1118_fu_181_p00;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln703_10_reg_1410[11 : 2] <= add_ln703_10_fu_990_p2[11 : 2];
        add_ln703_11_reg_1415[11 : 2] <= add_ln703_11_fu_996_p2[11 : 2];
        add_ln703_13_reg_1450[12 : 2] <= add_ln703_13_fu_1231_p2[12 : 2];
        add_ln703_16_reg_1420[11 : 2] <= add_ln703_16_fu_1002_p2[11 : 2];
        add_ln703_17_reg_1455[12 : 1] <= add_ln703_17_fu_1250_p2[12 : 1];
        add_ln703_18_reg_1425[11 : 1] <= add_ln703_18_fu_1008_p2[11 : 1];
        add_ln703_19_reg_1460[12 : 1] <= add_ln703_19_fu_1259_p2[12 : 1];
        add_ln703_20_reg_1430[11 : 1] <= add_ln703_20_fu_1014_p2[11 : 1];
        add_ln703_21_reg_1465[12 : 1] <= add_ln703_21_fu_1268_p2[12 : 1];
        add_ln703_2_reg_1435[12 : 1] <= add_ln703_2_fu_1184_p2[12 : 1];
        add_ln703_3_reg_1400[11 : 1] <= add_ln703_3_fu_978_p2[11 : 1];
        add_ln703_3_reg_1400_pp0_iter1_reg[11 : 1] <= add_ln703_3_reg_1400[11 : 1];
        add_ln703_5_reg_1440[12 : 1] <= add_ln703_5_fu_1200_p2[12 : 1];
        add_ln703_8_reg_1405[10 : 2] <= add_ln703_8_fu_984_p2[10 : 2];
        add_ln703_9_reg_1445[12 : 2] <= add_ln703_9_fu_1213_p2[12 : 2];
        add_ln703_reg_1395[11 : 1] <= add_ln703_fu_972_p2[11 : 1];
        data_0_V_read_3_reg_1370 <= data_0_V_read_int_reg;
        data_6_V_read_3_reg_1364 <= data_6_V_read_int_reg;
        data_8_V_read_3_reg_1358 <= data_8_V_read_int_reg;
        mul_ln1118_3_reg_433 <= mul_ln1118_3_fu_183_p2;
        mul_ln1118_reg_429 <= mul_ln1118_fu_181_p2;
        sub_ln1118_14_reg_1380 <= sub_ln1118_14_fu_866_p2;
        sub_ln1118_15_reg_1385[9 : 1] <= sub_ln1118_15_fu_884_p2[9 : 1];
        sub_ln1118_18_reg_1390 <= sub_ln1118_18_fu_936_p2;
        sub_ln1118_1_reg_1375[9 : 2] <= sub_ln1118_1_fu_467_p2[9 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg[15 : 1] <= sext_ln703_8_fu_1295_p1[15 : 1];
        ap_return_1_int_reg[15 : 2] <= sext_ln703_14_fu_1311_p1[15 : 2];
        ap_return_2_int_reg[15 : 1] <= sext_ln703_20_fu_1336_p1[15 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_V_read_int_reg <= data_0_V_read;
        data_10_V_read_int_reg <= data_10_V_read;
        data_11_V_read_int_reg <= data_11_V_read;
        data_13_V_read_int_reg <= data_13_V_read;
        data_14_V_read_int_reg <= data_14_V_read;
        data_15_V_read_int_reg <= data_15_V_read;
        data_16_V_read_int_reg <= data_16_V_read;
        data_17_V_read_int_reg <= data_17_V_read;
        data_18_V_read_int_reg <= data_18_V_read;
        data_19_V_read_int_reg <= data_19_V_read;
        data_1_V_read_int_reg <= data_1_V_read;
        data_2_V_read_int_reg <= data_2_V_read;
        data_5_V_read_int_reg <= data_5_V_read;
        data_6_V_read_int_reg <= data_6_V_read;
        data_8_V_read_int_reg <= data_8_V_read;
        data_9_V_read_int_reg <= data_9_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln703_8_fu_1295_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln703_14_fu_1311_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln703_20_fu_1336_p1;
    end
end

assign acc_1_V_fu_1305_p2 = ($signed(sext_ln703_13_fu_1302_p1) + $signed(sext_ln703_10_fu_1299_p1));

assign acc_2_V_fu_1330_p2 = ($signed(add_ln703_22_fu_1324_p2) + $signed(sext_ln703_17_fu_1315_p1));

assign add_ln703_10_fu_990_p2 = ($signed(sext_ln728_8_fu_770_p1) + $signed(sext_ln728_10_fu_842_p1));

assign add_ln703_11_fu_996_p2 = ($signed(zext_ln728_7_fu_968_p1) + $signed(12'd4032));

assign add_ln703_12_fu_1225_p2 = ($signed(sext_ln703_12_fu_1222_p1) + $signed(sext_ln728_11_fu_1166_p1));

assign add_ln703_13_fu_1231_p2 = ($signed(add_ln703_12_fu_1225_p2) + $signed(sext_ln703_11_fu_1219_p1));

assign add_ln703_15_fu_1237_p2 = ($signed(sext_ln728_1_fu_1064_p1) + $signed(sext_ln728_fu_1053_p1));

assign add_ln703_16_fu_1002_p2 = ($signed(sext_ln728_2_fu_499_p1) + $signed(sext_ln728_3_fu_529_p1));

assign add_ln703_17_fu_1250_p2 = ($signed(sext_ln703_16_fu_1247_p1) + $signed(sext_ln703_15_fu_1243_p1));

assign add_ln703_18_fu_1008_p2 = (zext_ln728_1_fu_605_p1 + zext_ln728_3_fu_659_p1);

assign add_ln703_19_fu_1259_p2 = (zext_ln703_1_fu_1256_p1 + zext_ln728_fu_1132_p1);

assign add_ln703_20_fu_1014_p2 = ($signed(sext_ln728_9_fu_800_p1) + $signed(sext_ln728_12_fu_916_p1));

assign add_ln703_21_fu_1268_p2 = ($signed(sext_ln703_18_fu_1265_p1) + $signed(sext_ln728_7_fu_1144_p1));

assign add_ln703_22_fu_1324_p2 = ($signed(sext_ln703_19_fu_1321_p1) + $signed(zext_ln703_2_fu_1318_p1));

assign add_ln703_2_fu_1184_p2 = ($signed(sext_ln703_4_fu_1181_p1) + $signed(sext_ln703_fu_1177_p1));

assign add_ln703_3_fu_978_p2 = (zext_ln728_4_fu_728_p1 + zext_ln728_5_fu_740_p1);

assign add_ln703_4_fu_1190_p2 = (shl_ln728_21_fu_1170_p3 + 11'd64);

assign add_ln703_5_fu_1200_p2 = ($signed(sext_ln703_6_fu_1196_p1) + $signed(zext_ln728_6_fu_1155_p1));

assign add_ln703_6_fu_1283_p2 = ($signed(sext_ln703_7_fu_1280_p1) + $signed(zext_ln703_fu_1277_p1));

assign add_ln703_7_fu_1289_p2 = ($signed(add_ln703_6_fu_1283_p2) + $signed(sext_ln703_5_fu_1274_p1));

assign add_ln703_8_fu_984_p2 = ($signed(sext_ln728_4_fu_571_p1) + $signed(zext_ln728_2_fu_617_p1));

assign add_ln703_9_fu_1213_p2 = ($signed(sext_ln703_9_fu_1210_p1) + $signed(zext_ln703_3_fu_1206_p1));

assign add_ln703_fu_972_p2 = ($signed(sext_ln728_5_fu_647_p1) + $signed(sext_ln728_6_fu_693_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign mul_ln1118_3_fu_183_p0 = zext_ln1116_4_fu_697_p1;

assign mul_ln1118_3_fu_183_p2 = ($signed({{1'b0}, {mul_ln1118_3_fu_183_p0}}) * $signed(-'hD));

assign mul_ln1118_fu_181_p0 = mul_ln1118_fu_181_p00;

assign mul_ln1118_fu_181_p00 = data_1_V_read_int_reg;

assign mul_ln1118_fu_181_p2 = ($signed({{1'b0}, {mul_ln1118_fu_181_p0}}) * $signed(-'hD));

assign sext_ln703_10_fu_1299_p1 = $signed(add_ln703_9_reg_1445);

assign sext_ln703_11_fu_1219_p1 = $signed(add_ln703_10_reg_1410);

assign sext_ln703_12_fu_1222_p1 = $signed(add_ln703_11_reg_1415);

assign sext_ln703_13_fu_1302_p1 = $signed(add_ln703_13_reg_1450);

assign sext_ln703_14_fu_1311_p1 = $signed(acc_1_V_fu_1305_p2);

assign sext_ln703_15_fu_1243_p1 = $signed(add_ln703_15_fu_1237_p2);

assign sext_ln703_16_fu_1247_p1 = $signed(add_ln703_16_reg_1420);

assign sext_ln703_17_fu_1315_p1 = $signed(add_ln703_17_reg_1455);

assign sext_ln703_18_fu_1265_p1 = $signed(add_ln703_20_reg_1430);

assign sext_ln703_19_fu_1321_p1 = $signed(add_ln703_21_reg_1465);

assign sext_ln703_20_fu_1336_p1 = $signed(acc_2_V_fu_1330_p2);

assign sext_ln703_4_fu_1181_p1 = $signed(add_ln703_reg_1395);

assign sext_ln703_5_fu_1274_p1 = $signed(add_ln703_2_reg_1435);

assign sext_ln703_6_fu_1196_p1 = $signed(add_ln703_4_fu_1190_p2);

assign sext_ln703_7_fu_1280_p1 = $signed(add_ln703_5_reg_1440);

assign sext_ln703_8_fu_1295_p1 = $signed(add_ln703_7_fu_1289_p2);

assign sext_ln703_9_fu_1210_p1 = $signed(add_ln703_8_reg_1405);

assign sext_ln703_fu_1177_p1 = $signed(shl_ln_fu_1037_p3);

assign sext_ln728_10_fu_842_p1 = $signed(shl_ln728_17_fu_834_p3);

assign sext_ln728_11_fu_1166_p1 = $signed(shl_ln728_19_fu_1159_p3);

assign sext_ln728_12_fu_916_p1 = $signed(shl_ln728_20_fu_908_p3);

assign sext_ln728_1_fu_1064_p1 = $signed(shl_ln728_2_fu_1057_p3);

assign sext_ln728_2_fu_499_p1 = $signed(shl_ln728_6_fu_491_p3);

assign sext_ln728_3_fu_529_p1 = $signed(shl_ln728_8_fu_521_p3);

assign sext_ln728_4_fu_571_p1 = $signed(shl_ln728_9_fu_563_p3);

assign sext_ln728_5_fu_647_p1 = $signed(shl_ln728_5_fu_639_p3);

assign sext_ln728_6_fu_693_p1 = $signed(shl_ln728_11_fu_685_p3);

assign sext_ln728_7_fu_1144_p1 = $signed(shl_ln728_13_fu_1136_p3);

assign sext_ln728_8_fu_770_p1 = $signed(shl_ln728_15_fu_762_p3);

assign sext_ln728_9_fu_800_p1 = $signed(shl_ln728_16_fu_792_p3);

assign sext_ln728_fu_1053_p1 = $signed(shl_ln728_1_fu_1045_p3);

assign shl_ln1118_10_fu_579_p3 = {{data_9_V_read_int_reg}, {4'd0}};

assign shl_ln1118_11_fu_621_p3 = {{data_11_V_read_int_reg}, {4'd0}};

assign shl_ln1118_12_fu_702_p3 = {{data_14_V_read_int_reg}, {4'd0}};

assign shl_ln1118_13_fu_744_p3 = {{data_15_V_read_int_reg}, {4'd0}};

assign shl_ln1118_14_fu_774_p3 = {{data_16_V_read_int_reg}, {4'd0}};

assign shl_ln1118_15_fu_804_p3 = {{data_17_V_read_int_reg}, {3'd0}};

assign shl_ln1118_16_fu_816_p3 = {{data_17_V_read_int_reg}, {1'd0}};

assign shl_ln1118_17_fu_854_p3 = {{data_18_V_read_int_reg}, {4'd0}};

assign shl_ln1118_18_fu_872_p3 = {{data_18_V_read_int_reg}, {1'd0}};

assign shl_ln1118_19_fu_942_p3 = {{data_19_V_read_int_reg}, {1'd0}};

assign shl_ln1118_1_fu_533_p3 = {{data_8_V_read_int_reg}, {3'd0}};

assign shl_ln1118_2_fu_545_p3 = {{data_8_V_read_int_reg}, {1'd0}};

assign shl_ln1118_3_fu_1020_p3 = {{data_0_V_read_3_reg_1370}, {4'd0}};

assign shl_ln1118_4_fu_443_p3 = {{data_2_V_read_int_reg}, {4'd0}};

assign shl_ln1118_5_fu_455_p3 = {{data_2_V_read_int_reg}, {2'd0}};

assign shl_ln1118_6_fu_1107_p3 = {{data_8_V_read_3_reg_1358}, {4'd0}};

assign shl_ln1118_7_fu_473_p3 = {{data_5_V_read_int_reg}, {4'd0}};

assign shl_ln1118_8_fu_1068_p3 = {{data_6_V_read_3_reg_1364}, {4'd0}};

assign shl_ln1118_9_fu_1079_p3 = {{data_6_V_read_3_reg_1364}, {2'd0}};

assign shl_ln1118_s_fu_503_p3 = {{data_6_V_read_int_reg}, {1'd0}};

assign shl_ln728_10_fu_651_p3 = {{data_11_V_read_int_reg}, {3'd0}};

assign shl_ln728_11_fu_685_p3 = {{sub_ln1118_9_fu_679_p2}, {1'd0}};

assign shl_ln728_12_fu_720_p3 = {{sub_ln1118_10_fu_714_p2}, {1'd0}};

assign shl_ln728_13_fu_1136_p3 = {{mul_ln1118_3_reg_433}, {1'd0}};

assign shl_ln728_14_fu_732_p3 = {{data_15_V_read_int_reg}, {3'd0}};

assign shl_ln728_15_fu_762_p3 = {{sub_ln1118_11_fu_756_p2}, {1'd0}};

assign shl_ln728_16_fu_792_p3 = {{sub_ln1118_12_fu_786_p2}, {1'd0}};

assign shl_ln728_17_fu_834_p3 = {{sub_ln1118_13_fu_828_p2}, {1'd0}};

assign shl_ln728_18_fu_1148_p3 = {{sub_ln1118_14_reg_1380}, {1'd0}};

assign shl_ln728_19_fu_1159_p3 = {{sub_ln1118_15_reg_1385}, {1'd0}};

assign shl_ln728_1_fu_1045_p3 = {{mul_ln1118_reg_429}, {1'd0}};

assign shl_ln728_20_fu_908_p3 = {{sub_ln1118_16_fu_902_p2}, {1'd0}};

assign shl_ln728_21_fu_1170_p3 = {{sub_ln1118_18_reg_1390}, {1'd0}};

assign shl_ln728_22_fu_960_p3 = {{sub_ln1118_17_fu_954_p2}, {1'd0}};

assign shl_ln728_2_fu_1057_p3 = {{sub_ln1118_1_reg_1375}, {1'd0}};

assign shl_ln728_3_fu_597_p3 = {{sub_ln1118_7_fu_591_p2}, {1'd0}};

assign shl_ln728_4_fu_609_p3 = {{data_10_V_read_int_reg}, {4'd0}};

assign shl_ln728_5_fu_639_p3 = {{sub_ln1118_8_fu_633_p2}, {1'd0}};

assign shl_ln728_6_fu_491_p3 = {{sub_ln1118_2_fu_485_p2}, {1'd0}};

assign shl_ln728_7_fu_1096_p3 = {{sub_ln1118_3_fu_1090_p2}, {1'd0}};

assign shl_ln728_8_fu_521_p3 = {{sub_ln1118_4_fu_515_p2}, {1'd0}};

assign shl_ln728_9_fu_563_p3 = {{sub_ln1118_5_fu_557_p2}, {1'd0}};

assign shl_ln728_s_fu_1124_p3 = {{sub_ln1118_6_fu_1118_p2}, {1'd0}};

assign shl_ln_fu_1037_p3 = {{sub_ln1118_fu_1031_p2}, {1'd0}};

assign sub_ln1118_10_fu_714_p2 = (zext_ln1118_13_fu_710_p1 - zext_ln1116_4_fu_697_p1);

assign sub_ln1118_11_fu_756_p2 = (10'd0 - zext_ln1118_14_fu_752_p1);

assign sub_ln1118_12_fu_786_p2 = (10'd0 - zext_ln1118_15_fu_782_p1);

assign sub_ln1118_13_fu_828_p2 = (zext_ln1118_17_fu_824_p1 - zext_ln1118_16_fu_812_p1);

assign sub_ln1118_14_fu_866_p2 = (zext_ln1118_19_fu_862_p1 - zext_ln1116_5_fu_846_p1);

assign sub_ln1118_15_fu_884_p2 = (zext_ln1118_20_fu_880_p1 - zext_ln1118_19_fu_862_p1);

assign sub_ln1118_16_fu_902_p2 = (zext_ln1118_18_fu_850_p1 - zext_ln1118_21_fu_898_p1);

assign sub_ln1118_17_fu_954_p2 = (zext_ln1118_22_fu_932_p1 - zext_ln1118_23_fu_950_p1);

assign sub_ln1118_18_fu_936_p2 = (zext_ln1116_6_fu_920_p1 - zext_ln1118_22_fu_932_p1);

assign sub_ln1118_1_fu_467_p2 = (zext_ln1118_2_fu_463_p1 - zext_ln1118_1_fu_451_p1);

assign sub_ln1118_2_fu_485_p2 = (10'd0 - zext_ln1118_3_fu_481_p1);

assign sub_ln1118_3_fu_1090_p2 = (zext_ln1118_4_fu_1075_p1 - zext_ln1118_5_fu_1086_p1);

assign sub_ln1118_4_fu_515_p2 = (7'd0 - zext_ln1118_6_fu_511_p1);

assign sub_ln1118_5_fu_557_p2 = (zext_ln1118_8_fu_553_p1 - zext_ln1118_7_fu_541_p1);

assign sub_ln1118_6_fu_1118_p2 = (zext_ln1118_9_fu_1114_p1 - zext_ln1116_1_fu_1104_p1);

assign sub_ln1118_7_fu_591_p2 = (zext_ln1118_10_fu_587_p1 - zext_ln1116_2_fu_575_p1);

assign sub_ln1118_8_fu_633_p2 = (10'd0 - zext_ln1118_11_fu_629_p1);

assign sub_ln1118_9_fu_679_p2 = (zext_ln1116_3_fu_663_p1 - zext_ln1118_12_fu_675_p1);

assign sub_ln1118_fu_1031_p2 = (10'd0 - zext_ln1118_fu_1027_p1);

assign tmp_1_fu_667_p3 = {{data_13_V_read_int_reg}, {4'd0}};

assign tmp_2_fu_890_p3 = {{data_18_V_read_int_reg}, {3'd0}};

assign tmp_3_fu_924_p3 = {{data_19_V_read_int_reg}, {4'd0}};

assign zext_ln1116_1_fu_1104_p1 = data_8_V_read_3_reg_1358;

assign zext_ln1116_2_fu_575_p1 = data_9_V_read_int_reg;

assign zext_ln1116_3_fu_663_p1 = data_13_V_read_int_reg;

assign zext_ln1116_4_fu_697_p1 = data_14_V_read_int_reg;

assign zext_ln1116_5_fu_846_p1 = data_18_V_read_int_reg;

assign zext_ln1116_6_fu_920_p1 = data_19_V_read_int_reg;

assign zext_ln1118_10_fu_587_p1 = shl_ln1118_10_fu_579_p3;

assign zext_ln1118_11_fu_629_p1 = shl_ln1118_11_fu_621_p3;

assign zext_ln1118_12_fu_675_p1 = tmp_1_fu_667_p3;

assign zext_ln1118_13_fu_710_p1 = shl_ln1118_12_fu_702_p3;

assign zext_ln1118_14_fu_752_p1 = shl_ln1118_13_fu_744_p3;

assign zext_ln1118_15_fu_782_p1 = shl_ln1118_14_fu_774_p3;

assign zext_ln1118_16_fu_812_p1 = shl_ln1118_15_fu_804_p3;

assign zext_ln1118_17_fu_824_p1 = shl_ln1118_16_fu_816_p3;

assign zext_ln1118_18_fu_850_p1 = data_18_V_read_int_reg;

assign zext_ln1118_19_fu_862_p1 = shl_ln1118_17_fu_854_p3;

assign zext_ln1118_1_fu_451_p1 = shl_ln1118_4_fu_443_p3;

assign zext_ln1118_20_fu_880_p1 = shl_ln1118_18_fu_872_p3;

assign zext_ln1118_21_fu_898_p1 = tmp_2_fu_890_p3;

assign zext_ln1118_22_fu_932_p1 = tmp_3_fu_924_p3;

assign zext_ln1118_23_fu_950_p1 = shl_ln1118_19_fu_942_p3;

assign zext_ln1118_2_fu_463_p1 = shl_ln1118_5_fu_455_p3;

assign zext_ln1118_3_fu_481_p1 = shl_ln1118_7_fu_473_p3;

assign zext_ln1118_4_fu_1075_p1 = shl_ln1118_8_fu_1068_p3;

assign zext_ln1118_5_fu_1086_p1 = shl_ln1118_9_fu_1079_p3;

assign zext_ln1118_6_fu_511_p1 = shl_ln1118_s_fu_503_p3;

assign zext_ln1118_7_fu_541_p1 = shl_ln1118_1_fu_533_p3;

assign zext_ln1118_8_fu_553_p1 = shl_ln1118_2_fu_545_p3;

assign zext_ln1118_9_fu_1114_p1 = shl_ln1118_6_fu_1107_p3;

assign zext_ln1118_fu_1027_p1 = shl_ln1118_3_fu_1020_p3;

assign zext_ln703_1_fu_1256_p1 = add_ln703_18_reg_1425;

assign zext_ln703_2_fu_1318_p1 = add_ln703_19_reg_1460;

assign zext_ln703_3_fu_1206_p1 = shl_ln728_7_fu_1096_p3;

assign zext_ln703_fu_1277_p1 = add_ln703_3_reg_1400_pp0_iter1_reg;

assign zext_ln728_1_fu_605_p1 = shl_ln728_3_fu_597_p3;

assign zext_ln728_2_fu_617_p1 = shl_ln728_4_fu_609_p3;

assign zext_ln728_3_fu_659_p1 = shl_ln728_10_fu_651_p3;

assign zext_ln728_4_fu_728_p1 = shl_ln728_12_fu_720_p3;

assign zext_ln728_5_fu_740_p1 = shl_ln728_14_fu_732_p3;

assign zext_ln728_6_fu_1155_p1 = shl_ln728_18_fu_1148_p3;

assign zext_ln728_7_fu_968_p1 = shl_ln728_22_fu_960_p3;

assign zext_ln728_fu_1132_p1 = shl_ln728_s_fu_1124_p3;

always @ (posedge ap_clk) begin
    sub_ln1118_1_reg_1375[1:0] <= 2'b00;
    sub_ln1118_15_reg_1385[0] <= 1'b0;
    add_ln703_reg_1395[0] <= 1'b0;
    add_ln703_3_reg_1400[0] <= 1'b0;
    add_ln703_3_reg_1400_pp0_iter1_reg[0] <= 1'b0;
    add_ln703_8_reg_1405[1:0] <= 2'b00;
    add_ln703_10_reg_1410[1:0] <= 2'b00;
    add_ln703_11_reg_1415[1:0] <= 2'b00;
    add_ln703_16_reg_1420[1:0] <= 2'b00;
    add_ln703_18_reg_1425[0] <= 1'b0;
    add_ln703_20_reg_1430[0] <= 1'b0;
    add_ln703_2_reg_1435[0] <= 1'b0;
    add_ln703_5_reg_1440[0] <= 1'b0;
    add_ln703_9_reg_1445[1:0] <= 2'b00;
    add_ln703_13_reg_1450[1:0] <= 2'b00;
    add_ln703_17_reg_1455[0] <= 1'b0;
    add_ln703_19_reg_1460[0] <= 1'b0;
    add_ln703_21_reg_1465[0] <= 1'b0;
    ap_return_0_int_reg[0] <= 1'b0;
    ap_return_1_int_reg[1:0] <= 2'b00;
    ap_return_2_int_reg[0] <= 1'b0;
end

endmodule //dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0
