Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    fc1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    fc1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    fc1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    fc2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    fc2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    output_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu2:
      Precision:
        result: fixed<16,6>
      Trace: false
    softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_Models/Basket/simple_model/hls_prj/keras_model.h5'
OutputDir: hls4ml_Models/Basket/simple_model/hls_prj
OutputPredictions: null
Part: xc7a35tcsg324
ProjectName: myproject
Stamp: ade2d0eA
Version: 1.0.0
