// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="NN_final,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a35t-csg324-3,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.334875,HLS_SYN_LAT=23,HLS_SYN_TPT=1,HLS_SYN_MEM=3,HLS_SYN_DSP=4,HLS_SYN_FF=4170,HLS_SYN_LUT=9900,HLS_VERSION=2019_2}" *)

module NN_final (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fc1_input_V_ap_vld,
        fc1_input_V,
        layer10_out_0_V,
        layer10_out_0_V_ap_vld,
        layer10_out_1_V,
        layer10_out_1_V_ap_vld,
        layer10_out_2_V,
        layer10_out_2_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   fc1_input_V_ap_vld;
input  [47:0] fc1_input_V;
output  [15:0] layer10_out_0_V;
output   layer10_out_0_V_ap_vld;
output  [15:0] layer10_out_1_V;
output   layer10_out_1_V_ap_vld;
output  [15:0] layer10_out_2_V;
output   layer10_out_2_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer10_out_0_V_ap_vld;
reg layer10_out_1_V_ap_vld;
reg layer10_out_2_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_idle_pp0;
reg    fc1_input_V_ap_vld_in_sig;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
reg    ap_block_pp0_stage0_11001;
reg   [47:0] fc1_input_V_preg;
reg   [47:0] fc1_input_V_in_sig;
reg    fc1_input_V_ap_vld_preg;
reg    fc1_input_V_blk_n;
wire    ap_block_pp0_stage0;
reg   [15:0] layer2_out_1_V_reg_435;
reg   [15:0] layer2_out_5_V_reg_440;
reg   [15:0] layer2_out_6_V_reg_445;
reg   [15:0] layer2_out_7_V_reg_450;
reg   [15:0] layer2_out_8_V_reg_455;
reg   [15:0] layer2_out_9_V_reg_460;
reg   [15:0] layer2_out_11_V_reg_465;
reg   [15:0] layer2_out_12_V_reg_470;
reg   [15:0] layer2_out_13_V_reg_475;
reg   [15:0] layer2_out_14_V_reg_480;
reg   [15:0] layer2_out_15_V_reg_485;
reg   [15:0] layer2_out_16_V_reg_490;
reg   [15:0] layer2_out_18_V_reg_495;
reg   [15:0] layer2_out_19_V_reg_500;
reg   [4:0] layer4_out_1_V_reg_505;
reg   [4:0] layer4_out_5_V_reg_510;
reg   [4:0] layer4_out_6_V_reg_515;
reg   [4:0] layer4_out_7_V_reg_520;
reg   [4:0] layer4_out_8_V_reg_525;
reg   [4:0] layer4_out_9_V_reg_530;
reg   [4:0] layer4_out_11_V_reg_535;
reg   [4:0] layer4_out_12_V_reg_540;
reg   [4:0] layer4_out_13_V_reg_545;
reg   [4:0] layer4_out_14_V_reg_550;
reg   [4:0] layer4_out_15_V_reg_555;
reg   [4:0] layer4_out_16_V_reg_560;
reg   [4:0] layer4_out_18_V_reg_565;
reg   [4:0] layer4_out_19_V_reg_570;
reg   [15:0] layer5_out_0_V_reg_575;
reg   [15:0] layer5_out_1_V_reg_580;
reg   [15:0] layer5_out_2_V_reg_585;
reg   [15:0] layer5_out_5_V_reg_590;
reg   [15:0] layer5_out_6_V_reg_595;
reg   [15:0] layer5_out_8_V_reg_600;
reg   [15:0] layer5_out_9_V_reg_605;
reg   [15:0] layer5_out_10_V_reg_610;
reg   [15:0] layer5_out_11_V_reg_615;
reg   [15:0] layer5_out_13_V_reg_620;
reg   [15:0] layer5_out_14_V_reg_625;
reg   [15:0] layer5_out_15_V_reg_630;
reg   [15:0] layer5_out_16_V_reg_635;
reg   [15:0] layer5_out_17_V_reg_640;
reg   [15:0] layer5_out_18_V_reg_645;
reg   [15:0] layer5_out_19_V_reg_650;
reg   [4:0] layer7_out_0_V_reg_655;
reg   [4:0] layer7_out_1_V_reg_660;
reg   [4:0] layer7_out_2_V_reg_665;
reg   [4:0] layer7_out_5_V_reg_670;
reg   [4:0] layer7_out_6_V_reg_675;
reg   [4:0] layer7_out_8_V_reg_680;
reg   [4:0] layer7_out_9_V_reg_685;
reg   [4:0] layer7_out_10_V_reg_690;
reg   [4:0] layer7_out_11_V_reg_695;
reg   [4:0] layer7_out_13_V_reg_700;
reg   [4:0] layer7_out_14_V_reg_705;
reg   [4:0] layer7_out_15_V_reg_710;
reg   [4:0] layer7_out_16_V_reg_715;
reg   [4:0] layer7_out_17_V_reg_720;
reg   [4:0] layer7_out_18_V_reg_725;
reg   [4:0] layer7_out_19_V_reg_730;
reg   [15:0] layer8_out_0_V_reg_735;
reg   [15:0] layer8_out_1_V_reg_740;
reg   [15:0] layer8_out_2_V_reg_745;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_0;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_1;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_2;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_3;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_4;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_5;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_6;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_7;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_8;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_9;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_10;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_11;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_12;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_13;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_14;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_15;
reg    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call39;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call39;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call39;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call39;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call39;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call39;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call39;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call39;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call39;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call39;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call39;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call39;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call39;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call39;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call39;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call39;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call39;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call39;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call39;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call39;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call39;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call39;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call39;
wire    ap_block_state24_pp0_stage0_iter23_ignore_call39;
reg    ap_block_pp0_stage0_11001_ignoreCallOp57;
wire    call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_ready;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_0;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_1;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_2;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_3;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_4;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_5;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_6;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_7;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_8;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_9;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_10;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_11;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_12;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_13;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_14;
wire   [4:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_15;
wire    call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_ready;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_0;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_1;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_2;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_3;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_4;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_5;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_6;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_7;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_8;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_9;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_10;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_11;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_12;
wire   [4:0] call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_13;
wire   [15:0] grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_0;
wire   [15:0] grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_1;
wire   [15:0] grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_2;
reg    grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call73;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call73;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call73;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call73;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call73;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call73;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call73;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call73;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call73;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call73;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call73;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call73;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call73;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call73;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call73;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call73;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call73;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call73;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call73;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call73;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call73;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call73;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call73;
wire    ap_block_state24_pp0_stage0_iter23_ignore_call73;
reg    ap_block_pp0_stage0_11001_ignoreCallOp95;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_0;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_1;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_2;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_3;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_4;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_5;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_6;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_7;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_8;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_9;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_10;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_11;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_12;
wire   [15:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_13;
reg    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call9;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call9;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call9;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call9;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call9;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call9;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call9;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call9;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call9;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call9;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call9;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call9;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call9;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call9;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call9;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call9;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call9;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call9;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call9;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call9;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call9;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call9;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call9;
wire    ap_block_state24_pp0_stage0_iter23_ignore_call9;
reg    ap_block_pp0_stage0_11001_ignoreCallOp26;
wire    grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start;
wire    grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_done;
wire    grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_idle;
wire    grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ready;
reg    grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ce;
wire   [15:0] grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_0;
wire   [15:0] grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_1;
wire   [15:0] grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_2;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call77;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call77;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call77;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call77;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call77;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call77;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call77;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call77;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call77;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call77;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call77;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call77;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call77;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call77;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call77;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call77;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call77;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call77;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call77;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call77;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call77;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call77;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call77;
wire    ap_block_state24_pp0_stage0_iter23_ignore_call77;
reg    ap_block_pp0_stage0_11001_ignoreCallOp102;
reg    grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start_reg;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to22;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 fc1_input_V_preg = 48'd0;
#0 fc1_input_V_ap_vld_preg = 1'b0;
#0 grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start_reg = 1'b0;
end

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0 grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_1_V_read(layer4_out_1_V_reg_505),
    .data_5_V_read(layer4_out_5_V_reg_510),
    .data_6_V_read(layer4_out_6_V_reg_515),
    .data_7_V_read(layer4_out_7_V_reg_520),
    .data_8_V_read(layer4_out_8_V_reg_525),
    .data_9_V_read(layer4_out_9_V_reg_530),
    .data_11_V_read(layer4_out_11_V_reg_535),
    .data_12_V_read(layer4_out_12_V_reg_540),
    .data_13_V_read(layer4_out_13_V_reg_545),
    .data_14_V_read(layer4_out_14_V_reg_550),
    .data_15_V_read(layer4_out_15_V_reg_555),
    .data_16_V_read(layer4_out_16_V_reg_560),
    .data_18_V_read(layer4_out_18_V_reg_565),
    .data_19_V_read(layer4_out_19_V_reg_570),
    .ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_13),
    .ap_return_14(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_14),
    .ap_return_15(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_15),
    .ap_ce(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_ce)
);

relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93(
    .ap_ready(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_ready),
    .data_0_V_read(layer5_out_0_V_reg_575),
    .data_1_V_read(layer5_out_1_V_reg_580),
    .data_2_V_read(layer5_out_2_V_reg_585),
    .data_5_V_read(layer5_out_5_V_reg_590),
    .data_6_V_read(layer5_out_6_V_reg_595),
    .data_8_V_read(layer5_out_8_V_reg_600),
    .data_9_V_read(layer5_out_9_V_reg_605),
    .data_10_V_read(layer5_out_10_V_reg_610),
    .data_11_V_read(layer5_out_11_V_reg_615),
    .data_13_V_read(layer5_out_13_V_reg_620),
    .data_14_V_read(layer5_out_14_V_reg_625),
    .data_15_V_read(layer5_out_15_V_reg_630),
    .data_16_V_read(layer5_out_16_V_reg_635),
    .data_17_V_read(layer5_out_17_V_reg_640),
    .data_18_V_read(layer5_out_18_V_reg_645),
    .data_19_V_read(layer5_out_19_V_reg_650),
    .ap_return_0(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_0),
    .ap_return_1(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_1),
    .ap_return_2(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_2),
    .ap_return_3(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_3),
    .ap_return_4(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_4),
    .ap_return_5(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_5),
    .ap_return_6(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_6),
    .ap_return_7(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_7),
    .ap_return_8(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_8),
    .ap_return_9(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_9),
    .ap_return_10(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_10),
    .ap_return_11(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_11),
    .ap_return_12(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_12),
    .ap_return_13(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_13),
    .ap_return_14(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_14),
    .ap_return_15(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_15)
);

relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113(
    .ap_ready(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_ready),
    .data_1_V_read(layer2_out_1_V_reg_435),
    .data_5_V_read(layer2_out_5_V_reg_440),
    .data_6_V_read(layer2_out_6_V_reg_445),
    .data_7_V_read(layer2_out_7_V_reg_450),
    .data_8_V_read(layer2_out_8_V_reg_455),
    .data_9_V_read(layer2_out_9_V_reg_460),
    .data_11_V_read(layer2_out_11_V_reg_465),
    .data_12_V_read(layer2_out_12_V_reg_470),
    .data_13_V_read(layer2_out_13_V_reg_475),
    .data_14_V_read(layer2_out_14_V_reg_480),
    .data_15_V_read(layer2_out_15_V_reg_485),
    .data_16_V_read(layer2_out_16_V_reg_490),
    .data_18_V_read(layer2_out_18_V_reg_495),
    .data_19_V_read(layer2_out_19_V_reg_500),
    .ap_return_0(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_0),
    .ap_return_1(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_1),
    .ap_return_2(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_2),
    .ap_return_3(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_3),
    .ap_return_4(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_4),
    .ap_return_5(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_5),
    .ap_return_6(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_6),
    .ap_return_7(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_7),
    .ap_return_8(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_8),
    .ap_return_9(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_9),
    .ap_return_10(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_10),
    .ap_return_11(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_11),
    .ap_return_12(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_12),
    .ap_return_13(call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_13)
);

dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0 grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(layer7_out_0_V_reg_655),
    .data_1_V_read(layer7_out_1_V_reg_660),
    .data_2_V_read(layer7_out_2_V_reg_665),
    .data_5_V_read(layer7_out_5_V_reg_670),
    .data_6_V_read(layer7_out_6_V_reg_675),
    .data_8_V_read(layer7_out_8_V_reg_680),
    .data_9_V_read(layer7_out_9_V_reg_685),
    .data_10_V_read(layer7_out_10_V_reg_690),
    .data_11_V_read(layer7_out_11_V_reg_695),
    .data_13_V_read(layer7_out_13_V_reg_700),
    .data_14_V_read(layer7_out_14_V_reg_705),
    .data_15_V_read(layer7_out_15_V_reg_710),
    .data_16_V_read(layer7_out_16_V_reg_715),
    .data_17_V_read(layer7_out_17_V_reg_720),
    .data_18_V_read(layer7_out_18_V_reg_725),
    .data_19_V_read(layer7_out_19_V_reg_730),
    .ap_return_0(grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_2),
    .ap_ce(grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_ce)
);

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1 grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_V_read(fc1_input_V_in_sig),
    .ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_13),
    .ap_ce(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_ce)
);

softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start),
    .ap_done(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_done),
    .ap_idle(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_idle),
    .ap_ready(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ready),
    .ap_ce(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ce),
    .data_0_V_read(layer8_out_0_V_reg_735),
    .data_1_V_read(layer8_out_1_V_reg_740),
    .data_2_V_read(layer8_out_2_V_reg_745),
    .ap_return_0(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_0),
    .ap_return_1(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_1),
    .ap_return_2(grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fc1_input_V_ap_vld_preg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            fc1_input_V_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (fc1_input_V_ap_vld == 1'b1))) begin
            fc1_input_V_ap_vld_preg <= fc1_input_V_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fc1_input_V_preg <= 48'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (fc1_input_V_ap_vld == 1'b1))) begin
            fc1_input_V_preg <= fc1_input_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ready == 1'b1)) begin
            grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer2_out_11_V_reg_465 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_6;
        layer2_out_12_V_reg_470 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_7;
        layer2_out_13_V_reg_475 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_8;
        layer2_out_14_V_reg_480 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_9;
        layer2_out_15_V_reg_485 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_10;
        layer2_out_16_V_reg_490 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_11;
        layer2_out_18_V_reg_495 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_12;
        layer2_out_19_V_reg_500 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_13;
        layer2_out_1_V_reg_435 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_0;
        layer2_out_5_V_reg_440 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_1;
        layer2_out_6_V_reg_445 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_2;
        layer2_out_7_V_reg_450 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_3;
        layer2_out_8_V_reg_455 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_4;
        layer2_out_9_V_reg_460 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_return_5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        layer4_out_11_V_reg_535 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_6;
        layer4_out_12_V_reg_540 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_7;
        layer4_out_13_V_reg_545 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_8;
        layer4_out_14_V_reg_550 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_9;
        layer4_out_15_V_reg_555 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_10;
        layer4_out_16_V_reg_560 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_11;
        layer4_out_18_V_reg_565 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_12;
        layer4_out_19_V_reg_570 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_13;
        layer4_out_1_V_reg_505 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_0;
        layer4_out_5_V_reg_510 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_1;
        layer4_out_6_V_reg_515 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_2;
        layer4_out_7_V_reg_520 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_3;
        layer4_out_8_V_reg_525 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_4;
        layer4_out_9_V_reg_530 <= call_ret1_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config4_s_fu_113_ap_return_5;
        layer5_out_0_V_reg_575 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_0;
        layer5_out_10_V_reg_610 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_7;
        layer5_out_11_V_reg_615 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_8;
        layer5_out_13_V_reg_620 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_9;
        layer5_out_14_V_reg_625 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_10;
        layer5_out_15_V_reg_630 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_11;
        layer5_out_16_V_reg_635 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_12;
        layer5_out_17_V_reg_640 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_13;
        layer5_out_18_V_reg_645 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_14;
        layer5_out_19_V_reg_650 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_15;
        layer5_out_1_V_reg_580 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_1;
        layer5_out_2_V_reg_585 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_2;
        layer5_out_5_V_reg_590 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_3;
        layer5_out_6_V_reg_595 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_4;
        layer5_out_8_V_reg_600 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_5;
        layer5_out_9_V_reg_605 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_return_6;
        layer7_out_0_V_reg_655 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_0;
        layer7_out_10_V_reg_690 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_7;
        layer7_out_11_V_reg_695 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_8;
        layer7_out_13_V_reg_700 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_9;
        layer7_out_14_V_reg_705 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_10;
        layer7_out_15_V_reg_710 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_11;
        layer7_out_16_V_reg_715 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_12;
        layer7_out_17_V_reg_720 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_13;
        layer7_out_18_V_reg_725 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_14;
        layer7_out_19_V_reg_730 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_15;
        layer7_out_1_V_reg_660 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_1;
        layer7_out_2_V_reg_665 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_2;
        layer7_out_5_V_reg_670 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_3;
        layer7_out_6_V_reg_675 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_4;
        layer7_out_8_V_reg_680 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_5;
        layer7_out_9_V_reg_685 <= call_ret3_relu_ap_fixed_16_6_5_3_0_ap_ufixed_5_0_4_0_0_relu_config7_s_fu_93_ap_return_6;
        layer8_out_0_V_reg_735 <= grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_0;
        layer8_out_1_V_reg_740 <= grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_1;
        layer8_out_2_V_reg_745 <= grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_return_2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to22 = 1'b1;
    end else begin
        ap_idle_pp0_0to22 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to22 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((fc1_input_V_ap_vld == 1'b1)) begin
        fc1_input_V_ap_vld_in_sig = fc1_input_V_ap_vld;
    end else begin
        fc1_input_V_ap_vld_in_sig = fc1_input_V_ap_vld_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        fc1_input_V_blk_n = fc1_input_V_ap_vld;
    end else begin
        fc1_input_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((fc1_input_V_ap_vld == 1'b1)) begin
        fc1_input_V_in_sig = fc1_input_V;
    end else begin
        fc1_input_V_in_sig = fc1_input_V_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp26) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_1_fu_151_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp57) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_75_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp95) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_fu_131_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ce = 1'b1;
    end else begin
        grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer10_out_0_V_ap_vld = 1'b1;
    end else begin
        layer10_out_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer10_out_1_V_ap_vld = 1'b1;
    end else begin
        layer10_out_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer10_out_2_V_ap_vld = 1'b1;
    end else begin
        layer10_out_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp102 = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp26 = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp57 = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp95 = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b1) & ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call39 = ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call73 = ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call77 = ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call9 = ((fc1_input_V_ap_vld_in_sig == 1'b0) | (ap_start == 1'b0));
end

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call39 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call77 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call9 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start = grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_start_reg;

assign layer10_out_0_V = grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_0;

assign layer10_out_1_V = grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_1;

assign layer10_out_2_V = grp_softmax_stable_ap_fixed_ap_fixed_16_2_5_3_0_softmax_config10_s_fu_157_ap_return_2;

endmodule //NN_final
